name: Build Server Docker Image

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'OldReferenceCode/**'
      - 'XMPP-ejabberd/**'
      - 'OldReferenceCode/**'
      - 'Files/Engine.ini'
      - 'UT4MasterServer.Web/**'
  push:
    paths-ignore:
      - '*.md'
      - 'OldReferenceCode/**'
      - 'XMPP-ejabberd/**'
      - 'OldReferenceCode/**'
      - 'Files/Engine.ini'
      - 'UT4MasterServer.Web/**'

env:
  IMAGE_NAME: ut4masterserver

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build --pull -t ${{ env.IMAGE_NAME }} -f ./UT4MasterServer/Dockerfile .
      - name: Clean Up
        run: docker image rm ${{ env.IMAGE_NAME }}
